### ISSUE TITLE
Training on my own data

### ISSUE THREAD

**Issue by acerio98** [Amir-Arsalan/Synthesize3DviaDepthOrSil#10]
When I try and train on my own dataset, I include files for all 20 viewpoints per the README, but when I perform random sampling on the manifold I get results (the 5x5 grids) that are the same for each viewpoint. However when I train with the same arguments on class data from ShapeNet Core through the provided link (e.g. headphones) then I am able to get expected results with different views for each viewpoint. Could you offer any ideas of what I might be doing wrong with my data? Thanks.

**Comment by Amir-Arsalan** [comment]
@acerio98 I'm not entirely sure what might be causing this but if the produced samples are sharp and are not blurry it probably means that the model is over-fitting the data. If the samples are pretty blurry you will need to give more data/time to the model to get trained.

**Comment by acerio98** [comment]
Okay, after some poking around I have an idea of what the problem may be. I'm training the model on a set of long, narrow objects (sword models) and my theory is that the network is only picking up on the very tip of the models since that is the only part that appears as a strong white in any of the depth maps, given that that part gets closest to the camera while rending the maps.

I guess my question now is whether there is any way to make the network more sensitive to  features in the depth maps that may not be as strong (i.e. features that appear in the gray range rather than pure white, as in the example below).

![model_1_Cam_6](https://user-images.githubusercontent.com/7104505/66441944-c528ce80-ea06-11e9-99b6-888bbd713bed.png)

Is this just a matter of giving the network more data or epochs to train, like you say? I'd appreciate any tips you could offer.

**Comment by Amir-Arsalan** [comment]
@acerio98 Sorry for getting back to you with a lot of delay. Somehow I missed your question here. The major things that contribute to getting sharper results (e.g. the model pays attention to small details) are a good model architecture, training the model longer and more importantly replace VAE with another generative model whose assumptions (i.e. regularization) does not cause the decoder to behave conservatively when mapping the latents to the output, as vanilla VAE does that. More data should help too.
