### ISSUE TITLE
How to compute the IoU

### ISSUE THREAD

**Issue by guoyan1991** [Amir-Arsalan/Synthesize3DviaDepthOrSil#4]
Hello, can you give me c code for calculating IoU? Or teach me how to calculate it? I looked at the process of calculating IoU in 3d-r2n2, but I still don't understand it. Looking forward to your reply.

**Comment by Amir-Arsalan** [comment]
I just realized that the C code is missing in the `zip-IoU.zip` file. I was originally thinking my co-author Haibin has given me both the C code and the executable. You may send him an email and ask him about the C code he used to compute IoU.

**Comment by guoyan1991** [comment]
I'll try it. Thank you very much！

**Comment by Amir-Arsalan** [comment]
@guoyan1991 If I remember correctly, he told me he uses 32^3 voxels to compute IoUs. Maybe you can write your own code to do that.
