### ISSUE TITLE
Surface 3D reconstruction of Point cloud 

### ISSUE THREAD

**Issue by guoyan1991** [Amir-Arsalan/Synthesize3DviaDepthOrSil#5]
Hello, could you tell me what is the method of converting point cloud into topology when calculating voxel IoU?

**Comment by Amir-Arsalan** [comment]
@guoyan1991 I'm not sure entirely sure about that part. @brotherhuang, could you please describe the method here more clearly?

**Comment by TigerWj** [comment]
Hello,the download link of  pre-trained models is unavailable. so,could you update it again? Thank you.

**Comment by TigerWj** [comment]
@guoyan1991  hello ,did you make it?(3D reconstruction)

**Comment by TigerWj** [comment]
@Amir-Arsalan  Hi, I want achieve Visualization in 3D，but
**when I do this below:**
 th 4_1_visualization.lua  
-inputDir 'xxxx/testExp/experiments/reconstruction/test/airplane/model1VP14-airplane' 
-outputDir 'xxxx' 
-experiment 'reconstruction'
-onlyOneCat 1

**then show:**
==> Projecting back the generated depth maps to obtain final point cloud representation for the category: airplane	
==> Done with getting 3D reconstruction for airplane. No of samples: 1. Time took: 0.0 minutes	
==> Done with creating all 3D reconstructions. No of total samples: 1. Total time: 0.1 minutes

**but ,finally,there is nothing in the output folder**

I hope you can guide me through this problem

**Comment by hualalala7458** [comment]
@TigerWj  I have the same question as yours, how did you solve it?

**Comment by Amir-Arsalan** [comment]
@TigerWj @hualalala7458 The Lua code might have some issues that I did not notice. Instead, you can compile the [3D reconstruction](https://github.com/Amir-Arsalan/Synthesize3DviaDepthOrSil/blob/master/zip-depth_render_reconstruction.zip) code and call the built executable to get the reconstructions.
