### ISSUE TITLE
getIoU

### ISSUE THREAD

**Issue by fairuzsafwan** [Amir-Arsalan/Synthesize3DviaDepthOrSil#7]
Hi Amir,

I tried getting the IoU for quantitative evaluations. 
Requirements are all met and runs without any error.
Requirements:
1. Visual C++ Redistributable for Visual Studio 2015 (installed-but not from the provided link because a newer version is already installed when installing Visual Studio 2015, 
Version 14.0.24215 was installed instead of the provided Version 14.0.23026)
2. Visual C++ Redistributable Packages for Visual Studio 2013 (installed from the provided link)
3. Python 3.7 (installed)
4. Anaconda with Python 3.6 (installed)

Paths of the .ply files in the test folder are as below:
test/model-userData-1/model-userData-1-or.ply
test/model-userData-1/model-userData-1-rec.ply
test/model-userData-2/model-userData-1-or.ply
test/model-userData-2/model-userData-1-rec.ply
test/model-userData-3/model-userData-1-or.ply
test/model-userData-3/model-userData-1-rec.ply
etc

However, I'm only getting 
"----------------average------------------
-nan(ind)"

I believed that the issue might be lying somewhere in the getIoU.exe because it seems to run
without any errors till the end.
However, I could not further verify the problem since the getIoU is a binary.

Have you come across the same problem before?
Any pointers/advise is really much appreciated.

Thanks in advance

Best regards,
Safwan

**Comment by Amir-Arsalan** [comment]
I never got such an error when running the code but if you still haven't been able to get the code to work and you are sure that you are not changing anything in the point cloud files manually, you may contact @brotherhuang as he wrote the IoU calculation code.

**Comment by fairuzsafwan** [comment]
Thanks Amir.

I will contact him then.
