### ISSUE TITLE
Download question

### ISSUE THREAD

**Issue by TigerWj** [Amir-Arsalan/Synthesize3DviaDepthOrSil#8]
Hello,the download link of pre-trained models is unavailable. so,could you update it again? Thank you

**Comment by Amir-Arsalan** [comment]
I just clicked on the link and it works. Which model are you looking for?

https://www.amazon.com/clouddrive/share/oDnklSMldXWd3CrzSu5ndfl0GMIBffRfvMAFvkWkz5x

**Comment by TigerWj** [comment]
Thank you, but the link in the parameter module still seems to be unavailable(I don't know if it is the reason for my network)

**Comment by Amir-Arsalan** [comment]
Sorry I'm not sure what you mean by "parameter module". Could you be more clear?
