### ISSUE TITLE
Pre-trained models' link broken

### ISSUE THREAD

**Issue by kampta** [Amir-Arsalan/Synthesize3DviaDepthOrSil#9]
It seems the [link](https://www.amazon.com/clouddrive/share/ar4GuXPAPtUBb4NRbjjbrzNB3BLL2On5nD4jYhFbdTi?_encoding=UTF8&mgh=1&ref_=cd_ph_share_link_copy) to pre-trained models is broken. Would it be possible for you to share it again?

**Comment by Amir-Arsalan** [comment]
@kampta It's strange cause I never change the path in my Amazon Drive. Fixed now ... .

**Comment by kampta** [comment]
Thanks!
